
# Names of variables used in analysis -------------------------------------

elvars <- c(
  "IND_YRS", "diur_any",
  "FSI_NYHA",
  "F21", "F22", "VG1", "VG4", "VOG",
  "FSI_PROBNP",
  "EKG_FIB_FLUT",
  "cor_cur_any",
  "ace_any", "arb_any",
  "FSI_HEM", "FSI_BMI",
  "FSI_SBP", "mra_any", "bbl_any", "cc_any",
  "stroke_cur_any",
  "EKG_VRATE",
  "MDRD",
  "FSI_K",
  "cancer_any",
  "liver_any"
)

tabvars <- c(
  "IND_GEN",
  "IND_YRS",
  "IND_ETHNIC",
  "indexYear_cat",
  "ef",
  "EFgroup57",
  "EFgroupfda",
  "EFgroup6462",
  "VG10",
  "FSI_NYHA",
  "FSI_NYHA_cat",
  "EKG_FIB_FLUT",
  "F21", "F22", "VG1", "VG4", "VOG",
  "FSI_SBP", "FSI_DBP",
  "map", "map_cat",
  "EKG_VRATE",
  "EKG_VRATE_cat",
  "MDRD",
  "MDRD_cat",
  "MDRD_cat2",
  "FSI_HEM",
  "FSI_HEM_cat",
  "FSI_PROBNP",
  "FSI_PROBNP_cat",
  "FSI_K",
  "raas",
  "mra_any",
  "diur_any",
  "nitrate_any",
  "antiplat_any",
  "anticoag_any",
  "statin_any",
  "bbl_any",
  "cc_any",
  "smoking",
  "FSI_BMI",
  "FSI_BMI_cat",
  "FSI_BMI_cat2",
  "hypertension_any",
  "diabetes_any",
  "ihd_any",
  "cor_cur_any",
  "pci_cabg_any",
  "pvd_any",
  "stroke_any",
  "stroke_cur_any",
  "valvular_any",
  "heartvalvesurgery_any",
  "lung_any",
  "liver_any",
  "cancer_any",
  "syncope_any",
  "FSI_MIN1",
  "FSI_MAJ7",
  "FSI_MAJ3",
  "FSI_MIN3"
)


modvars <- c(
  "IND_GEN",
  "IND_YRS",
  "FSI_NYHA_cat",
  "map_cat",
  "EKG_VRATE_cat",
  "FSI_BMI_cat2",
  "MDRD_cat2",
  "FSI_PROBNP_cat",
  "FSI_HEM_cat",
  "diabetes_any",
  "hypertension_any",
  "ihd_any",
  "EKG_FIB_FLUT",
  "lung_any",
  "cancer_any",
  "stroke_any",
  "valvular_any",
  # "liver_any", too few values
  "raas",
  "mra_any",
  "bbl_any",
  "statin_any",
  "antiplat_any",
  "anticoag_any",
  # "syncope_any", too few values
  "FSI_MIN1",
  "FSI_MAJ7",
  "FSI_MAJ3",
  "FSI_MIN3"
)

adjmodvars <- c(
  "IND_GEN",
  "IND_YRS",
  "FSI_NYHA_cat",
  "MDRD_cat2",
  "FSI_PROBNP_cat",
  "diabetes_any",
  "hypertension_any",
  "ihd_any",
  "EKG_FIB_FLUT",
  "raas",
  "mra_any",
  "bbl_any"
)
