```{r}

incexlFunc <- function(pop, exportname, export = FALSE) {
  if (exists("flowtab")) rm(flowtab, envir = .GlobalEnv)
  if (exists("impdata_tmp")) rm(impdata_tmp, envir = .GlobalEnv)
  if (exists("pdata_tmp")) rm(pdata_tmp, envir = .GlobalEnv)

  impdata_tmp <- impdata %>%
    filter(!!enexpr(pop))
  pdata_tmp <- pdata %>%
    filter(!!enexpr(pop))

  Nimp <- nrow(impdata_tmp)
  Ncomp <- nrow(pdata_tmp %>% filter(nomissing))
  Nel <- nrow(pdata_tmp)


  flowtab <- data.frame("No of patients", Nimp, Ncomp, Nel)
  colnames(flowtab) <- c("", rep("out", 3))

  flowtab <- rbind(flowtab, funcIEfake("**Inclusion criteria**"))

  ## USE HIS (prior to index), HIS2 (index), HIS3 () combo

  flowtab <- rbind(flowtab, funcIEfake("1. Written informed consent must be obtained before any assessment is performed"))

  flowtab <- rbind(
    flowtab,
    funcIETab(
      ievar = "ie_in_pragscen_in2",
      paste0("2. >=50 years of age", footnote_marker_symbol(1)),
      impdata_tmp, pdata_tmp
    )
  )

  flowtab <- rbind(
    flowtab,
    funcIEfake("3. LVEF >=45% by echocardiography during the screening epoch, or within 6 months prior to screening visit (in primary inclusion)")
  )

  ## ska MRA vara med diuretia inkl MRA (UP)
  flowtab <- rbind(flowtab, funcIETab(
    ievar = "ie_in4",
    "4. Diuretic treatment",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_in_pragscen_in5",
    paste0("5. NYHA II-IV", footnote_marker_symbol(1)),
    impdata_tmp, pdata_tmp
  ))


  # Waiting for reply.
  flowtab <- rbind(flowtab, funcIETab(
    "ie_in6",
    "6. Structural heart disease",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_in_pragscen_in7",
    paste0(
      "7. NT-proBNP/(AF) (all patients cosidered to be HF hospitalizised within previous 9 months", footnote_marker_symbol(1)
    ),
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (literal scenario) only inclusion criteria",
    "^ie_in",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (pragmatic scenario) only inclusion criteria",
    "^ie_in_pragscen",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("**Exclusion criteria**"))

  flowtab <- rbind(flowtab, funcIEfake("1. Any prior echocardiographic measurement of LVEF <40%"))

  ## not HIS_COR since then will include historic MI
  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex2",
    "2. Coronary syndrome prior to follow-up visit (at HIS2 or HIS3)",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("3. Any clinical event within the 6 months prior to visit 1 that could have reduced the LVEF 
           (e.g., MI, CABG), unless an echocardiographic measurement was performed after the event 
           confirming the LVEF to be >=45%"))


  flowtab <- rbind(flowtab, funcIEfake("4. Current acute decompensated HF requiring augmented therapy with diuretic agents, vasodilator agents, and/or inotropic drugs"))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex5",
    "5. Patients who require treatment with both an ACEI and an ARB",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("6. History of hypersensitivity to any of the study drugs or to drugs of similar chemical classes"))


  flowtab <- rbind(flowtab, funcIEfake("7. Known history of angioedema"))

  flowtab <- rbind(flowtab, funcIEfake("8. a. Severe pulmonary disease including COPD (i.e.,requiring home oxygen, chronic nebulizer therapy, or chronic oral steroid therapy or hospitalized for pulmonary decompensation within 12 months)"))

  flowtab <- rbind(
    flowtab, funcIETab(
      "ie_ex8b", "8. b. Hemoglobin <10 g/dL",
      impdata_tmp, pdata_tmp
    )
  )

  flowtab <- rbind(
    flowtab, funcIETab(
      "ie_ex8c", "8. c. BMI >40 kg/m2",
      impdata_tmp, pdata_tmp
    )
  )

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex9a",
    "9. a. SBP >= 180 mmHg",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex9b",
    "9. b. SBP >150 mmHg and <180 mmHg at baseline, 
         unless the patient is receiving 3 or more antihypertensive drugs",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex_pragscen_ex9c",
    paste0("9. c. SBP <110/100 mmHg", footnote_marker_symbol(1)),
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("9. d. SBP <100 mm Hg or symptomatic hypotension as determined by the investigator at visit 103 or visit 199/201"))

  flowtab <- rbind(flowtab, funcIEfake("10. Use of other investigational drugs at the time of enrollment, 
           or within 30 days or 5 half-lives of enrollment, whichever is longer"))

  flowtab <- rbind(flowtab, funcIEfake("11. Patients with history of any dilated cardiomyopathy, including peripartum cardiomyopathy, 
           chemotherapy-induced cardiomyopathy, or viral myocarditis "))

  flowtab <- rbind(flowtab, funcIEfake("12. Evidence of right-sided HF in the absence of left-sided structural heart disease"))

  flowtab <- rbind(flowtab, funcIEfake("13. Known pericardial constriction, genetic hypertrophic cardiomyopathy, or infiltrative cardiomyopathy"))

  flowtab <- rbind(flowtab, funcIEfake("14. Clinically significant congenital heart disease that could be the cause of the 
           patient’s symptoms and signs of HF"))

  flowtab <- rbind(flowtab, funcIEfake("15. Presence of hemodynamically significant valvular heart disease in the opinion of the investigator"))

  ## not HIS_ASSSTROKE since then will include historic stroke
  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex16",
    "16. Stroke prior to follow-up visit (at HIS2 or HIS3)",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("17. Coronary or carotid artery disease or valvular heart disease likely to require 
           surgical or percutaneous intervention during the trial"))

  # Don't use HIS3_RHYATTACH but below for consitency with SwedeHF
  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex18",
    "18. AF and HR >110",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("19. Patients with a cardiac resynchronization therapy device"))

  flowtab <- rbind(flowtab, funcIEfake("20. Patients with prior major organ transplant"))

  flowtab <- rbind(flowtab, funcIEfake("21. Any surgical or medical condition that in the opinion of the investigator 
           may place the patient at higher risk from his/her participation in the study or 
           is likely to prevent the patient from complying with the requirements of the 
           study or completing the study"))

  flowtab <- rbind(flowtab, funcIEfake("22. Any surgical or medical condition that might significantly alter the absorption, 
           distribution, metabolism, or excretion of study drugs, including but not limited 
           to any of the following: any history of pancreatic injury, pancreatitis, or 
           evidence of impaired pancreatic function/injury within the past 5 years"))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex23",
    "23. History of Hepatic disease",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex_pragscen_ex24a",
    paste0("24. a. eGFR (MDRD) < 30", footnote_marker_symbol(1)),
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("24. b. eGFR <25 ml/min/1.73 m2 at visit 103 or visit 199/201"))
  flowtab <- rbind(flowtab, funcIEfake("24. c. eGFR reduction >35% (compared with visit 1) at visit 103 or visit 199/201"))
  flowtab <- rbind(flowtab, funcIEfake("25. Presence of known functionally significant bilateral renal artery stenosis"))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex26a",
    "26. a. Potassium > 5.2",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("26. b. Serum potassium >5.4 mmol/l (mEq/l) at visit 103 or visit 199/201 "))

  flowtab <- rbind(flowtab, funcIEfake("27. Death within 3 years from non-CV casue"))

  flowtab <- rbind(flowtab, funcIEfake("28. History of noncompliance to medical regimens and patients who are considered potentially unreliable"))

  flowtab <- rbind(flowtab, funcIEfake("29. History or evidence of drug or alcohol abuse within the past 12 months"))

  flowtab <- rbind(flowtab, funcIEfake("30. Persons directly involved in the execution of this protocol"))

  flowtab <- rbind(flowtab, funcIETab(
    "ie_ex31",
    "31. Malignancy (other than localized basal or squamous cell carcinoma of the 
         skin or localized prostate cancer) within the past 5 years prior to index",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcIEfake("32. Pregnant or nursing (lactating) women, where pregnancy is defined as the state of 
           a female after conception and until the termination of gestation, confirmmed by 
           a positive human chorionic gonadotropin laboratory test"))
  flowtab <- rbind(flowtab, funcIEfake("33. Women of child-bearing potential, defined as all women physiologically 
           capable of becoming pregnant, unless they are using highly effective methods of 
           contraception during dosing and for 7 days off study drug"))

  colnames(flowtab) <- c(
    "Criteria",
    "Imputed data",
    "Complete case",
    "Missing as eligible"
  )

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (literal scenario) only exclusion criteria",
    "^ie_ex",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (pragmatic scenario) only exclusion criteria",
    "^ie_ex_pragscen",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (literal scenario) all criteria",
    "^ie_in|^ie_ex",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (pragmatic scenario)",
    "^ie_in_pragscen|^ie_ex_pragscen",
    impdata_tmp, pdata_tmp
  ))


  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5) and eGFR (excl 24a))",
    "ie_in_pragscen_in5|ie_ex_pragscen_ex24a",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5) and NP (incl 7))",
    "ie_in_pragscen_in5|ie_in_pragscen_in7",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5) and diuretics (incl 4))",
    "ie_in_pragscen_in5|ie_in4",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5) and structural (incl 6))",
    "ie_in_pragscen_in5|ie_in6",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5), NP (incl7) and diuretics (incl 4))",
    "ie_in_pragscen_in5|ie_in_pragscen_in7|ie_in4",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5), eGFR (excl 24a) and NP (incl7))",
    "ie_in_pragscen_in5|ie_ex_pragscen_ex24a|ie_in_pragscen_in7",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5), eGFR (excl 24a) and diuretics (incl 4))",
    "ie_in_pragscen_in5|ie_ex_pragscen_ex24a|ie_in4",
    impdata_tmp, pdata_tmp
  ))

  flowtab <- rbind(flowtab, funcSumIEAll(
    "Eligible (label scenario with NYHA (incl 5), eGFR (excl 24a), diuretics (incl 4) and NP (incl7))",
    "ie_in_pragscen_in5|ie_ex_pragscen_ex24a|ie_in4|ie_in_pragscen_in7",
    impdata_tmp, pdata_tmp
  ))

  # Export to Excel
  
  if (export) {
    write.xlsx(flowtab, paste0("./output/tabs/tabincexc_karen_", exportname, "_", Sys.Date(), ".xlsx"),
      rowNames = FALSE
    )
  }

  footnote(mykable(flowtab), # %>%
    # pack_rows("Inclusion criteria", 2, 8) %>%
    # pack_rows("Exclusion criteria", 9, nrow(flowtab) - 2),
    symbol = c(
      "Included in pragmatic scenario"
    )
  )
}
```

### Overall
```{r ietaboverall}
incexlFunc(!is.na(IND_YRS), exportname = "tot", export = TRUE)
```

### Subgroup: Females
```{r ietabf}
incexlFunc(IND_GEN == "Female", exportname = "female", export = TRUE)
```

### Subgroup: Males
```{r ietabm}
incexlFunc(IND_GEN == "Male")
```

### Subgroup: EF <= 57%
```{r ietabu57}
incexlFunc(EFgroup57 == "<=57", exportname = "under57", export = TRUE)
```

### Subgroup: EF > 57%
```{r ietabo57}
incexlFunc(EFgroup57 == ">57")
```
