```{r}

tabElFunc <- function(pop, nofda = FALSE, nr = NULL, export = FALSE, exportname) {

  ### Literal scenario
  pdata_tmp <- pdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi = rowSums(select(
      .,
      matches("^ie_in|^ie_ex")
    ) == FALSE) > 0)
  impdata_tmp <- impdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi_imp = rowSums(select(
      .,
      matches("^ie_in|^ie_ex")
    ) == FALSE) > 0)

  tabeldata.lit <- left_join(pdata_tmp,
    impdata_tmp %>% select(PatID, eligi_imp),
    by = "PatID"
  )

  tab.imp.lit <- CreateTableOne(
    vars = tabvars,
    strata = "eligi_imp",
    data = tabeldata.lit
  )

  tab.imp.lit <- print(tab.imp.lit,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.comp.lit <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.lit %>% filter(nomissing)
  )

  tab.comp.lit <- print(tab.comp.lit,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.missasel.lit <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.lit
  )

  tab.missasel.lit <- print(tab.missasel.lit,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  ### Pragmatic scenario

  pdata_tmp <- pdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi = rowSums(select(
      .,
      matches("^ie_in_pragscen|^ie_in_labscen_in_pragscen|^ie_ex_pragscen|^ie_ex_labscen_ex_pragscen")
    ) == FALSE) > 0)
  impdata_tmp <- impdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi_imp = rowSums(select(
      .,
      matches("^ie_in_pragscen|^ie_in_labscen_in_pragscen|^ie_ex_pragscen|^ie_ex_labscen_ex_pragscen")
    ) == FALSE) > 0)

  tabeldata.prag <- left_join(
    pdata_tmp,
    impdata_tmp %>% select(PatID, eligi_imp),
    by = "PatID"
  ) %>%
    mutate_if(is_character, factor)

  tab.imp.prag <- CreateTableOne(
    vars = tabvars,
    strata = "eligi_imp",
    data = tabeldata.prag
  )

  tab.imp.prag <- print(tab.imp.prag,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.comp.prag <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.prag %>% filter(nomissing)
  )

  tab.comp.prag <- print(tab.comp.prag,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.missasel.prag <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.prag
  )

  tab.missasel.prag <- print(tab.missasel.prag,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  ### FDA scenario

  if (!nofda){
  pdata_tmp <- pdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi = fda_ie_in3 == FALSE | ie_in_pragscen_in5 == FALSE)
  impdata_tmp <- impdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi_imp = fda_ie_in3 == FALSE | ie_in_pragscen_in5 == FALSE)

  tabeldata.fda <- left_join(
    pdata_tmp,
    impdata_tmp %>% select(PatID, eligi_imp),
    by = "PatID"
  ) %>%
    mutate_if(is_character, factor)

  tab.imp.fda <- CreateTableOne(
    vars = tabvars,
    strata = "eligi_imp",
    data = tabeldata.fda
  )

  tab.imp.fda <- print(tab.imp.fda,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.comp.fda <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.fda %>% filter(nomissing)
  )

  tab.comp.fda <- print(tab.comp.fda,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.missasel.fda <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.fda
  )

  tab.missasel.fda <- print(tab.missasel.fda,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )
  
  ### 64/62 scenario

  pdata_tmp <- pdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi = ef6462_ie_in3 == FALSE | ie_in_pragscen_in5 == FALSE)
  impdata_tmp <- impdata %>%
    filter(!!enexpr(pop)) %>%
    mutate(eligi_imp = ef6462_ie_in3 == FALSE | ie_in_pragscen_in5 == FALSE)

  tabeldata.ef6462 <- left_join(
    pdata_tmp,
    impdata_tmp %>% select(PatID, eligi_imp),
    by = "PatID"
  ) %>%
    mutate_if(is_character, factor)

  tab.imp.ef6462 <- CreateTableOne(
    vars = tabvars,
    strata = "eligi_imp",
    data = tabeldata.ef6462
  )

  tab.imp.ef6462 <- print(tab.imp.ef6462,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.comp.ef6462 <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.ef6462 %>% filter(nomissing)
  )

  tab.comp.ef6462 <- print(tab.comp.ef6462,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab.missasel.ef6462 <- CreateTableOne(
    vars = tabvars,
    strata = "eligi",
    data = tabeldata.ef6462
  )

  tab.missasel.ef6462 <- print(tab.missasel.ef6462,
    varLabels = TRUE, missing = FALSE, printToggle = FALSE,
    nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )
  }
  
  if (nofda){
  all <- cbind(
    tab.imp.lit[, 1:3], tab.comp.lit[, 1:3], tab.missasel.lit[, 1:3],
    tab.imp.prag[, 1:3], tab.comp.prag[, 1:3], tab.missasel.prag[, 1:3]
  )
  } else{
    all <- cbind(
    tab.imp.lit[, 1:3], tab.comp.lit[, 1:3], tab.missasel.lit[, 1:3],
    tab.imp.prag[, 1:3], tab.comp.prag[, 1:3], tab.missasel.prag[, 1:3],
    tab.imp.fda[, 1:3], tab.comp.fda[, 1:3], tab.missasel.fda[, 1:3],
    tab.imp.ef6462[, 1:3], tab.comp.ef6462[, 1:3], tab.missasel.ef6462[, 1:3]
  ) 
  }

  colnames(all) <- c(
    rep(c("Eligible", "Not eligible", "p-value"), ifelse(nofda, 6, 12))
  )

  ## Export to Excel
  if (export) write.xlsx(all, paste0("./output/tabs/tabByEligibilty_karen_", exportname, "_", Sys.Date(), ".xlsx"), rowNames = TRUE)

  rownamesadj <- rownames(all)

  ## white space removed in kable function. Add HTML space.
  rownamesadj <- sub("^ ", "&nbsp;", rownamesadj)

  rownames(all) <- rownamesadj


  if (nofda){
  myHeader <- c(
    " " = 1, "Imputed data" = 3, "Complete case" = 3, "Missing as eligible" = 3,
    "Imputed data" = 3, "Complete case" = 3, "Missing as eligible" = 3
  )
  names(myHeader) <- c(
    " ", "Imputed data", "Complete case", "Missing as eligible",
    "Imputed data", "Complete case", "Missing as eligible"
  )

  myHeader2 <- c(" " = 1, "Literal scenario" = 9, "Pragmatic scenario" = 9)
  names(myHeader2) <- c(" ", "Literal scenario", "Pragmatic scenario")
  } else{
      myHeader <- c(
    " " = 1, "Imputed data" = 3, "Complete case" = 3, "Missing as eligible" = 3,
    "Imputed data" = 3, "Complete case" = 3, "Missing as eligible" = 3,
    "Imputed data" = 3, "Complete case" = 3, "Missing as eligible" = 3,
    "Imputed data" = 3, "Complete case" = 3, "Missing as eligible" = 3
  )
  names(myHeader) <- c(
    " ", "Imputed data", "Complete case", "Missing as eligible",
    "Imputed data", "Complete case", "Missing as eligible", 
    "Imputed data", "Complete case", "Missing as eligible", 
    "Imputed data", "Complete case", "Missing as eligible"
  )

  myHeader2 <- c(" " = 1, "Literal scenario" = 9, "Pragmatic scenario" = 9, "FDA scenario" = 9, "EF 64/62% scenario" = 9)
  names(myHeader2) <- c(" ", "Literal scenario", "Pragmatic scenario", "FDA scenario", "EF 64/62% scenario")
  }

  footnote(mykable(all, row.names = TRUE) %>%
    add_header_above(myHeader) %>%
    add_header_above(myHeader2),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi2-test and continous variables are presented with median [q1-q3] and tested with Mann-Whitney U test",
    "Note that other variables that are subsets or in other ways related to the variables used in the eligibilty criteria should be viewed with caution"
  )
  )
}
```

### Overall
```{r Elbaseoverall}
tabElFunc(!is.na(IND_YRS), export = T, exportname = "tot")
```

### Subgroup: Females
```{r Elbasef}
tabElFunc(IND_GEN == "Female")
```

### Subgroup: Males
```{r Elbasem}
tabElFunc(IND_GEN == "Male")
```

### Subgroup: EF <= 57%
```{r Elbaseu57}
tabElFunc(EFgroup57 == "<=57")
```

### Subgroup: EF > 57%
```{r Elbaseo57}
tabElFunc(EFgroup57 == ">57", nofda = TRUE)
```

